### ISSUE TITLE
Montage CoverageCheck failing

### ISSUE THREAD

**Issue by simoneriggi** [SKA-INAF/scutout#1]
mCoverageCheck in old Montage version (<6) misses entries in table produced with mImgtbl utility. 
Issue is likely due to blank spaces inserted before the first column field (3 given when 2 expected?).
This behavior seems to be fixed in Montage v6.

**Comment by cbordiu** [comment]
We are having trouble with VGPS. mCoverageCheck fails so no cutouts are extracted for this survey. We tested SGPS and works fine.

**Comment by simoneriggi** [comment]
Is the issue related to WCS header in VGPS? In case send me a log.

****************************************************************
Simone Riggi, PhD
INAF, Osservatorio Astrofisico di Catania
Via S. Sofia 78
95123, Catania - Italy
phone:  +39 095 7332 extension 282 (or 310)
e-mail: simone.riggi@gmail.com,
            sriggi@inaf.it <sriggi@oact.inaf.it>,
            sriggi@pec.it <simone.riggi@ct.infn.it>
skype: simone.riggi
****************************************************************


Il giorno lun 18 mag 2020 alle ore 12:17 Cristóbal Bordiú <
notifications@github.com> ha scritto:

**Comment by cbordiu** [comment]
Finally, we discovered that the problem is related to the number of axes in the header. Apparently mCoverageCheck is not able to handle files with NAXIS > 2. It seems to be a design decision, as they say in "Supported File Formats" that it only works with 2D images: http://montage.ipac.caltech.edu/docs/supported.html.
